spring:
  datasource:
    url: ${POSTGRESQL_URL}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

supabase:
  s3:
    endpoint-url: "https://glrawoqhdlardyagmzih.storage.supabase.co/storage/v1/s3"
    region: "ap-southeast-1"
    access-key-id: ${SUPABASE_S3_KEY_ID}
    secret-access-key: ${SUPABASE_SECRET_ACCESS_KEY}
    bucket-name: "job-finder-service"